Repository pivotal-cf/docs-partials, pull requests merged in 2020-09, with the labels that each got.

#25 Removes messaging-nats
  subnavs/_pivotalcf-subnav-2-10.erb
  subnavs/_pivotalcf-subnav-2-11.erb
  subnavs/_pivotalcf-subnav-2-7.erb
  subnavs/_pivotalcf-subnav-2-8.erb
  subnavs/_pivotalcf-subnav-2-9.erb
Labels: scheduled

#24 Update networking related docs.
  core/2-10/_router_app_identity_verification.html.md.erb
  core/2-11/_router_app_identity_verification.html.md.erb
  core/2-7/_router_app_identity_verification.html.md.erb
  core/2-8/_router_app_identity_verification.html.md.erb
  core/2-9/_router_app_identity_verification.html.md.erb
Labels: scheduled

#26 Removes Beta Feature: Dynamic Egress Policies
  core/2-11/_dynamic-egress.html.md.erb
  subnavs/_pivotalcf-subnav-2-11.erb
Labels: scheduled

#27 Add new KPI for last_successful_backup for MySQL
  mysql/monitoring/kpis-metrics/_all-kpis.html.erb
Labels: unscheduled

#28 Consolidate TCP Routing pages
  subnavs/_pivotalcf-subnav-2-10.erb
  subnavs/_pivotalcf-subnav-2-11.erb
  subnavs/_pivotalcf-subnav-2-7.erb
  subnavs/_pivotalcf-subnav-2-8.erb
  subnavs/_pivotalcf-subnav-2-9.erb
Labels: unscheduled

#29 Remove redundant gorouter arch doc
  subnavs/_pivotalcf-subnav-2-10.erb
  subnavs/_pivotalcf-subnav-2-11.erb
  subnavs/_pivotalcf-subnav-2-7.erb
  subnavs/_pivotalcf-subnav-2-8.erb
  subnavs/_pivotalcf-subnav-2-9.erb
Labels: in progress

#30 Update UAA docs to explain the new uri encoding option
  core/2-7/_uaa.html.md.erb
Labels: scheduled
