Repository pivotal-cf/docs-partials, pull requests merged in 2020-10, with the labels that each got.

#31 Remove "Skip SSL Certificate Verification"
  core/2-11/_networking-is.html.md.erb
  core/2-11/_networking-master.html.md.erb
  core/2-11/_ssl_termin_gorouter_lb_pcf.html.md.erb
  core/2-11/_ssl_termin_gorouter_pcf.html.md.erb
  core/2-11/_ssl_termin_haproxy_pcf.html.md.erb
  core/2-11/_ssl_termin_lb_only_pcf.html.md.erb
  core/2-11/_ssl_verification.html.md.erb
Labels: scheduled

#32 Update link to docs for modifying TCP ports
  core/2-10/_tcp_routing_enable.html.md.erb
  core/2-11/_tcp_routing_enable.html.md.erb
  core/2-7/_tcp_routing_enable.html.md.erb
  core/2-8/_tcp_routing_enable.html.md.erb
  core/2-9/_tcp_routing_enable.html.md.erb
Labels: unscheduled

#33 Add instructions for configuring age of audit events pruned from CAPI
  core/2-11/_cloud-controller.html.md.erb
Labels: unscheduled

#36 Add instructions for configuring age of audit events pruned from CAPI
  core/2-8/_cloud-controller.html.md.erb
Labels: unscheduled

#37 Add instructions for configuring age of audit events pruned from CAPI
  core/2-7/_cloud-controller.html.md.erb
Labels: unscheduled

#35 Add instructions for configuring age of audit events pruned from CAPI
  core/2-9/_cloud-controller.html.md.erb
Labels: unscheduled

#34 Add instructions for configuring age of audit events pruned from CAPI
  core/2-10/_cloud-controller.html.md.erb
Labels: unscheduled

#38 Update Gorouter drain timeout description
  core/2-10/_networking-master.html.md.erb
  core/2-11/_networking-master.html.md.erb
  core/2-7/_networking-master.html.md.erb
  core/2-8/_networking-master.html.md.erb
  core/2-9/_networking-master.html.md.erb
Labels: unscheduled

#39 Add link to CF CLI reference guide to subnavigation for TAS 2.10 and
  subnavs/_pivotalcf-subnav-2-10.erb
Labels: unscheduled

#40 Revert "Add link to CF CLI reference guide to subnavigation for TAS 2.10 and"
  subnavs/_pivotalcf-subnav-2-10.erb
Labels: unscheduled

#41 Add v7 reference guide to subnav for tas 2.11
  subnavs/_pivotalcf-subnav-2-11.erb
Labels: unscheduled

#43 Update _mysql_bootstrapping.html.md.erb
  mysql/_mysql_bootstrapping.html.md.erb
Labels: unscheduled

#42 Correct terminology, typos, and grammar of cert rotation partial.
  certs/_rotating_services_tls_ca.html.md.erb
Labels: scheduled

#44 clarify "maximum file upload size" is affecting buildpacks
  core/2-10/_application_developer_controls.html.md.erb
  core/2-11/_application_developer_controls.html.md.erb
  core/2-7/_application_developer_controls.html.md.erb
  core/2-8/_application_developer_controls.html.md.erb
  core/2-9/_application_developer_controls.html.md.erb
Labels: in progress
