Repository pivotal-cf/docs-partials, pull requests merged in 2021-02, with the labels that each got.

#53 Add docs for the router ca cert properties
  core/2-10/_networking-is.html.md.erb
  core/2-10/_router_ca_certs_new.html.md.erb
  core/2-10/_router_ca_certs_old.html.md.erb
  core/2-11/_networking-is.html.md.erb
  core/2-11/_router_ca_certs.html.md.erb
  core/2-7/_networking-is.html.md.erb
  core/2-7/_router_ca_certs_new.html.md.erb
  core/2-7/_router_ca_certs_old.html.md.erb
  core/2-9/_networking-is.html.md.erb
  core/2-9/_router_ca_certs_new.html.md.erb
  core/2-9/_router_ca_certs_old.html.md.erb
Labels: in progress

#54 Update docs for s3 filestore config
  core/2-11/_filestore_s3_config.html.md.erb
Labels: scheduled

#57 Remove **beta** tag from App log rate limit for 2.11
  core/2-11/_application_container_config.html.md.erb
Labels: unscheduled
